### ISSUE TITLE
Labels for deeplab

### ISSUE THREAD

**Issue by roflcoopter** [PINTO0309/TPU-Posenet#1]
I am wondering what labels were used for the deeplab model?

It outputs some 0 but mostly 9 when no object is in the image which corresponds to ```background``` and ```chair``` in the official deeplab model.

Were different labels used for this model?

**Comment by PINTO0309** [comment]
@roflcoopter 
I used the following items.
**https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md**

And I diverted the label of the Pascal VOC dataset.
