### ISSUE TITLE
about FPS on raspberry pi

### ISSUE THREAD

**Issue by willfu** [PINTO0309/TPU-Posenet#2]
@PINTO0309 thanks for the work.  I am curious about the frame rate on raspberry pi.  do you have any data for that? the demo video are all from PC, right?

**Comment by PINTO0309** [comment]
Yes. Only the results verified on the PC were posted in the README. I got Pi4 the other day so I will try to verify it when I have time.

**Comment by willfu** [comment]
thanks for the reply, is CPU the bottleneck? or the io? as you are the expert ;)

**Comment by PINTO0309** [comment]
To put it simply, it is USB2.0 communication speed and CPU performance. Although it is a Japanese article, I would like to introduce the verification article of my acquaintance that I think is useful for you.

**[Edge TPU USB Accelerator analysis-I/O data transfer - Qiita - iwatake2222](https://qiita.com/iwatake2222/items/922f02893355b30dab2e)**

**[Analysis of Edge TPU USB Accelerator-Operation and model structure - Qiita - iwatake2222](https://qiita.com/iwatake2222/items/c3a63027d44434633922)**

**Comment by willfu** [comment]
Thanks for the introduction, which is based on jetson nano and tpu, I will also have a test.

**Comment by PINTO0309** [comment]
Pi4 + TPU x3 (Deeplabv3 + PoseNet + MobileNetV2-SSD)
The PiCamera settings don't seem to work. The shooting speed has become very slow...
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33194443/68640316-af00b780-054a-11ea-9ee3-2a5c12366212.gif)

**Comment by willfu** [comment]
thanks for the sharing. is this the result of tpux3 ? very strange...

**Comment by PINTO0309** [comment]
This is a sample of TPUx3. Because the camera shooting rate is only 10 FPS, the camera shooting speed is slower than inference. I think it works faster if the camera is set up correctly. Note that when 3 TPUs are used, all 4 Cores of the CPU are used up, so the CPU pre-processing and post-processing overhead is the bottleneck.

**Comment by willfu** [comment]
ok. Got it. thanks.
